trigger:
 - dev

pool:
  vmImage: 'windows-latest'

workspace:
  clean: all

steps:
 - task: NodeTool@0
   inputs:
    versionspec: "16.x"
    displayName: "Install Node.Js"

 - task: NPM@1
   inputs: 
    commad : "install"
    displayName: "NPM Installing"

 - task: NPM@1
   inputs:
    command: custom
    customCommand: "run build"
   displayName: "Building the App"

 - task: NPM@1
   inputs: 
    command:
    customCommand: "run test"
   displayName: "Testing App"

 - task: NPM@1
   inputs: 
    command:
    customCommand: "run lint"
   displayName: "Lint App"
 